name: GitHub Profile Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  push: {branches: [main]}
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 General
        uses: lowlighter/metrics@latest
        with:
          filename: general-metrics.svg
          token: ${{ secrets.GH_TOKEN }}
          config_order: base.header, lines, followup, languages, calendar
          config_display: large
            
        # base
          base: header
          base_indepth: yes

        # languages 
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
        #   plugin_languages_indepth: yes
        #   plugin_languages_analysis_timeout: 60
        #   plugin_languages_sections: most-used, recently-used
        #   plugin_languages_threshold: 2%

        # followup
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

        # calendar
          plugin_calendar: yes
          plugin_calendar_limit: 3
